### ISSUE TITLE
Missing last bit of UART transmit

### ISSUE THREAD

**Issue by TerribleKraal** [IntergatedCircuits/DebugDongleFW#1]
Hi !
I'm having an issue with the VCP part of the dongle.
When I'm sending 'U' over a terminal like putty, and looking at the scope output on PA2 (USART2_TX), I can see that the last bit is missing because I receive 0xD5 instead of 0x55. At first I thought it was the _WFI instruction in the main while loop that was happening too fast, but putting it in comment didn't solve the issue. Then I looked in the USART_prvDmaTransmitRedirect function and there is no check of the TC flag of USART, which needs to be checked before deactivating the DMA. Do you have any idea on this ?

**Comment by TerribleKraal** [comment]
So my analysis may be wrong. But what is really strange is that if I tie together RX and TX, the output on putty is correct, i.e. when I type U I receive U. This is what I get on Tx @ 115200bps
![uart_u](https://user-images.githubusercontent.com/13867766/40364090-aa3fd914-5dd1-11e8-949d-a687f0d3a90f.png)

**Comment by benedekkupper** [comment]
The `__WFI()` command only stops the processor clocking, peripherals are unaffected by default. `USART_eTransmit_DMA()` - unlike `USART_eSend_DMA()` - indeed doesn't check for TC flag at the end of the transfer, and returns as soon as the last byte is transferred to the USART peripheral and it's transmission begins. However, consecutive `USART_eTransmit_DMA()` calls will wait for TXE flag before writing to the peripheral.
That being said, I could also observe the same behavior. After some investigation I figured out the problem: the USART word length was incorrectly configured. That is why 'U' was looped back correctly - 0xAA however would end up as 0x2A. The specific error was this line in *xpd_usart.c*:
`uint8_t ucFrameSize = ucDataSize + (eParity != USART_PARITY_NONE) ? 1 : 0;`
ucFrameSize was 1, as the ? operator apparently doesn't have precedence over the + operator.
The line should look like this:
`uint8_t ucFrameSize = ucDataSize + ((eParity != USART_PARITY_NONE) ? 1 : 0);`

This error is corrected on STM32_XPD master, please check on your side that the UART characters are as expected.

**Comment by TerribleKraal** [comment]
Thank you for the quick and great support !
The VCP works flawlessly now.
