### ISSUE TITLE
(not an issue) VCP INF driver for win 8 and older

### ISSUE THREAD

**Issue by TerribleKraal** [IntergatedCircuits/DebugDongleFW#3]
Hi,

Thank you for the correction made to the VCP, I will test them as soon as possible and update you on the outcome.
On a side note, do you happen to have by any chance a driver file for the dongle for win 8 and older ?
On my win 10 PC everything is working as it should, but on some older machine I tried the ST VCP driver but it failed to send back the content of the UART to the USB pipe.
Any idea ?

**Comment by benedekkupper** [comment]
Can't you manually select the Serial Port driver during Update firmware procedure from Device Manager?

You are only using the VCP function of the dongle right? In that case I would try different values for the device and interface classes in the USB descriptors. Try the following modifications first:
- comment out `USBD_DFU_MountInterface()` and `USBD_HID_MountInterface()` calls in *App/usb_device.c*
- put the bold values from the USB device descriptor from http://www.usb.org/developers/docs/whitepapers/iadclasscode_r10.pdf to `usbd_deviceDesc` fields in *USBDevice/Device/Src/usbd_desc.c*

**Comment by TerribleKraal** [comment]
Hi,
I did try to select manually a signed driver (each time after having modified the VIP/PID to reflect the driver), but to no avail. Using the suggestion above did not change anything at all.
Funny thing is that the VCP driver from ST prevents the dongle to transmit back the UART to USB, while the arduino driver works only for a few chars (less than 16, after that it does not anything).
In each cases the transmission from USB to USART was working as it should have. It is only the way back that is faulty.
I will try some other changes to see if I find something...

In any case thank you for your help and have a good day,
Kraal

**Comment by TerribleKraal** [comment]
Moreover, when sniffing the USB traffic with a software on windows 7 64-bits, I can see that there is no USB answer from the dongle.

**Comment by benedekkupper** [comment]
My next suggestion would be to try installing a serial driver with [Zadig](https://zadig.akeo.ie/).

What do you mean by no USB answer? You could open the port successfully, and send down OUT data, yet no IN data is coming back?

**Comment by TerribleKraal** [comment]
I'll try Zadig.

Regarding IN data, I only get one partial IN packet (I linked the usart Rx and Tx with a wire to ease the debug), after that there are no IN data coming to the host. However all the OUT packet are treated and sent over usart without any issues.

Thanks for the support.

**Comment by TerribleKraal** [comment]
Small update : Zadig did not help at all.

**Comment by benedekkupper** [comment]
So this issue popped up on our side as well, and I wasn't able to resolve the problem with the above suggestions either. I have been thinking about more alternatives to test, I'll list them here as reference, and I'll update the ticket when we've succeeded:
1. Don't mount any other interfaces other than the VCP
2. Change the device descriptor's class:subclass:protocol to 2:2:1 (`usbd_deviceDesc`)
3. Remove the IAD from the CDC descriptor list (`cdc_desc`)
4. `#define USBD_CDC_NOTEP_USED 1` in `usbd_config.h`
5. Set the CDC endpoints as: in=0x81, out=0x01, notif=0x82
6. Set the VID:PID to 0x0483:0x5740

At this point the device describes itself identical to ST's CDC example, and further compatibility issues can then be directed towards ST.

**Comment by benedekkupper** [comment]
These modifications proved to be successful after the ST Virtual Com Port Driver was manually selected as the device driver (on a Windows 7 machine).
