### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by aleksmarcelo** [IntergatedCircuits/DebugDongleFW#4]
Hello!

I am getting the error below when i try to compile:

mkdir build_200_200
/usr/bin/arm-none-eabi-gcc -c -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -DUSBD_VID=0x200 -DUSBD_PID=0x200 -DHW_REV= -IBSP -IApp -ICharger -ISensor -IVCP -IHidReportDef/include -IUSBDevice/Include -IUSBDevice/PDs/STM32_XPD -ISTM32_XPD/CMSIS/Include -ISTM32_XPD/CMSIS/Device/ST/STM32F4xx/Include -ISTM32_XPD/STM32F4_XPD/inc -O3 -Wall -fdata-sections -ffunction-sections -std=gnu11 -MMD -MP -MF"build_200_200/bsp_usart.d" -MT"build_200_200/bsp_usart.d" -Wa,-a,-ad,-alms=build_200_200/bsp_usart.lst BSP/bsp_usart.c -o build_200_200/bsp_usart.o
In file included from BSP/bsp_usart.c:23:0:
**BSP/bsp_io.h:34:13: error: operator '>' has no left operand
 #if (HW_REV > 0xA)**

**Comment by aleksmarcelo** [comment]
Forced in the Makefile 
```
VID=200
PID=200
HW_REV=1

# Build path
BUILD_DIR = build_$(VID)_$(PID)

##++----  Target configuration  ----++##

CORE = m4
SERIES = STM32F4
```

and then getting :
```
BSP/bsp_usart.c:    NVIC_SetPriorityConfig(DMA1_Channel4_5_IRQn, 0, 0);
BSP/bsp_usart.c:    NVIC_EnableIRQ(DMA1_Channel4_5_IRQn);
BSP/bsp_usart.c:    NVIC_DisableIRQ(DMA1_Channel4_5_IRQn);
BSP/STM32F042F6.ioc:NVIC.DMA1_Channel4_5_IRQn=true\:0\:0\:false\:false\:true\:true
```

It seems that the code is not completellly prepared to compile use the STM32F4 MCUs right ?

DMA1_Channel4_5_IRQn is defeined in stm32f042x6.h but not  in stm32f407xx.h 

Looking forward to test the code !-D

**Comment by benedekkupper** [comment]
If you get a compile error on a revision that compiled on the Travis CI server, you should first check the differences between your make arguments to the ones in .travis.yml. In your case the problem was not assigning the HW_REV any numeric value.

This project was made for this specific MCU (STM32F042) because this is the cheapest that can do the job. Of course the application is reusable, all you need to do is duplicate my BSP folder and replace the hardware bindings to your platform. Other projects have an STM32F4 BSP, e.g. [this one](https://github.com/IntergatedCircuits/IPoverUSB/tree/master/BSP_STM32F4xx). If you only intend to use the USB-UART relay, you only have to modify the pin, IRQ and DMA assignments, and also fill the `Channel` field of the DMA init structure.

**Comment by aleksmarcelo** [comment]
Thank you ! 

We are developing using the STM32F4 Discovery board, so We are using the **stm32f407vgt6 MCU** .

We are working in a huge system and we will need to implement a USB composite device, so searching i've found your code. It seems to be an awesome solution .

**Do  you have some documents about the code, so we could minimize the learning curve and help you with the development ?**

Anyway it seems to be a very good approach to implement composite devices using the STM32 MCU family.

ps: After the development, resolving the all technical issues, we will get the cheapest MCU too.

**Comment by benedekkupper** [comment]
Do you mean the USBDevice stack or this DebugDongle project in particular?

It also depends on the use case, so are you developing further device classes, or in any way extending the stack? If not, then the examples and the doxygen documentation should be enough. Generally about the USB operation you can find good resources online (e.g. USB Made Simple / USB in a Nutshell). I mainly relied on the official USB specifications when writing the library, they are available online as well.

**Comment by aleksmarcelo** [comment]
I meant the USBDevice !  

I am using the STM32F4 because we need to have USB HOST;  it will be used to connect  smartphones. 

We are using the same books, but we are still learning how to develop the code using the STM32 MCUs. The **stm32 cubex** makes this task easier, but we still need to create a USB composite device and what you made seems to be awesome ! 
**It is very difficult to find information specific about how to implement composite devices with  stm32 MCUs !**   

marcelo.aleks _at_ google mail

**Comment by benedekkupper** [comment]
Well in case you want to consult me on specific USB or STM32 related topics you can contact me via email, it's listed on my profile.

**Comment by aleksmarcelo** [comment]
If it will not bother you, soon i would like to ask you some help !

Thank you !
